### ISSUE TITLE
Orientation lock is not reset during navigation between pages

### ISSUE THREAD

**Issue by alexshalamov** [intel/generic-sensor-demos#66]
Introduced by https://github.com/intel/generic-sensor-demos/commit/8ae7f0732af39170f04c64cd3a0ed81c2cc85efc

@kaixinjxq @rakuco please take a look.

**Comment by kenchris** [comment]
Running into some spec or browser bugs, bad behavior.

- You might want an change event handler but not call it in some calls to lock(), but the change event is fired after the lock promise resolves
- lock to 180 succeeds even though it doesn't rotate on Android and you then don't get change event

@kaixinjxq want to create test cases for wpt and report to Chrome/spec?

**Comment by rakuco** [comment]
> Running into some spec or browser bugs, bad behavior.

An easily reproducible bug, for example: with the phone in portrait mode, rotate to 180 then try rotating to 90. The first rotation does nothing but enter fullscreen mode, the second rotation works for a second or 2 then resets everything.

**Comment by kenchris** [comment]
Different variations with 180 fails:

270 - 180 - 90 fail
90 - 180 - 270 fail
180 - 90 fail
90 - 180 - 0 fail

It fails with AbortError. As 180 (portrait-secondary) completes with success without changing orientation, it makes sense if you read the spec text:

https://w3c.github.io/screen-orientation/#dfn-apply-an-orientation-lock

```
If one of the browsing contexts's document's pending promise is not null:
Let doc be the document which has a not null pending promise.
Reject doc's pending promise with DOMException whose name is AbortError.
Set doc's pending promise to null .
```

There is probably a pending promise that was never dealt with as it just "completed"

**Comment by rakuco** [comment]
I've filed #72 to keep track of all these orientation locking bugs.

**Comment by kenchris** [comment]
Surely looks like a Chrome bug, given that lock('portrait-secondary') succeeds but doesn't rotate and therefore doesn't send 'change' event.

Different variations with 180 (portrait secondary) fails, eg.

270 - 180 - 90 fail
90 - 180 - 270 fail
180 - 90 fail
90 - 180 - 0 fail

It fails with AbortError. As 180 (portrait-secondary) completes with success without changing orientation, it makes sense if you read the spec text:

https://w3c.github.io/screen-orientation/#dfn-apply-an-orientation-lock

```
If one of the browsing contexts's document's pending promise is not null:
Let doc be the document which has a not null pending promise.
Reject doc's pending promise with DOMException whose name is AbortError.
Set doc's pending promise to null .
```

There is probably a pending promise that was never dealt with as it just "completed"

Additional annoyance with the orientation lock API, is that the promise resolves before the event is sent. This makes it hard to default handlers that you don't want to call in certain cases, because if you remove the handler then there is no good place to add it back in, because if you do after the promise gets resolves, it might get called as the event is still pending :-( Would be good to file on the spec, plus might also then make sense for the unlock to return a promise.
